server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://google/${DB_NAME:lunara_masterdata}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&ipTypes=${CLOUD_SQL_IP_TYPES:PUBLIC}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

app.jwt.secret=${APP_JWT_SECRET}
