FROM maven:3.9.9-eclipse-temurin-8 AS builder
WORKDIR /workspace
COPY pom.xml pom.xml
COPY identity-service identity-service
COPY masterdata-service masterdata-service
COPY inventory-service inventory-service
RUN mvn -q -pl inventory-service -am -DskipTests package

FROM eclipse-temurin:8-jre
WORKDIR /app
COPY --from=builder /workspace/inventory-service/target/inventory-service-1.0.0.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java","-jar","/app/app.jar"]
