substitutions:
  _REGION: us-central1
  _REPOSITORY: hotel-inventory
  _SERVICE_NAME: rooms-service
  _TAG: latest
  _ENV_VARS_FILE: cloud-run/env.rooms.yaml

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - rooms-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --port
      - "8080"
      - --allow-unauthenticated
      - --env-vars-file
      - ${_ENV_VARS_FILE}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
